# This is a basic workflow to help you get started with Actions

name: Docker Robotframework API Testing Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      #Login to docker registry 
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin 
      
      # Builds the docker image
      - name: docker build
        run: docker build -t docker-api-robotframework:0.0.${{ github.run_number }} -t docker-api-robotframework:latest .
      
      # Runs the tests
      - name: docker run tests
        run: >
             docker run --rm
             --user $(id -u):$(id -g) \
             -v $GITHUB_WORKSPACE/tests:/home/robot/tests \
             -v $GITHUB_WORKSPACE/results:/home/robot/results \
             -v $GITHUB_WORKSPACE/libs:/home/robot/libs \
             docker-api-robotframework:latest
             
      # Push image
      - name: docker push
        run: docker push docker-api-robotframework:0.0.${{ github.run_number }}
        run: docker push docker-api-robotframework:latest
